name: dart_jwt
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.6.2
  lints: ^2.0.1
  test: ^1.21.0
